<a href="https://colab.research.google.com/github/hafezi1403/Hafezi/blob/main/book2_section4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Load libraries
import numpy as np
from scipy import sparse

In [2]:
# Create a matrix
matrix = np.array([[0, 0],
 [0, 1],
 [3, 0]])
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [3]:
# View sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [4]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
# View original sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [5]:
# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [6]:
# Load library
import numpy as np
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Select third element of vector
vector[2]

3

In [7]:
# Select second row, second column
matrix[1,1]

5

In [8]:
# Select all elements of a vector
vector[:]


array([1, 2, 3, 4, 5, 6])

In [9]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [10]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [11]:
# Select the last element
vector[-1]

6

In [12]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [14]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]])
# View number of rows and columns
matrix.shape

(3, 4)

In [15]:
# View number of elements (rows * columns)
matrix.size

12

In [16]:
# View number of dimensions
matrix.ndim

2

In [17]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Create function that adds 100 to something
add_100 = lambda i: i + 100
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [18]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [19]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Return maximum element
np.max(matrix)

9

In [20]:
# Return minimum element
np.min(matrix)

1

In [21]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [22]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

In [23]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Return mean
np.mean(matrix)

5.0

In [24]:
# Return variance
np.var(matrix)

6.666666666666667

In [25]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [26]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

In [27]:
# Load library
import numpy as np
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 [10, 11, 12]])
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [28]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [29]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [30]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [31]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 1, 1],
 [1, 1, 10],
 [1, 1, 15]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

In [34]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])
# Return determinant of matrix
np.linalg.det(matrix)

0.0

In [35]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])
# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [36]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [37]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

In [38]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])
# Return trace
matrix.trace()

14

In [39]:
# Return diagonal and sum elements
sum(matrix.diagonal())

14

In [40]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, -1, 3],
 [1, 1, 6],
 [3, 8, 9]])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
# View eigenvalues
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [41]:
# View eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

In [42]:
# Load library
import numpy as np
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
# Calculate dot product
np.dot(vector_a, vector_b)

32

In [43]:
# Calculate dot product
vector_a @ vector_b

32

In [44]:
# Load library
import numpy as np
# Create matrix
matrix_a = np.array([[1, 1, 1],
 [1, 1, 1],
 [1, 1, 2]])
# Create matrix
matrix_b = np.array([[1, 3, 1],
 [1, 3, 1],
 [1, 3, 8]])
# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [45]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [46]:
# Add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [47]:
# Load library
import numpy as np
# Create matrix
matrix_a = np.array([[1, 1],
 [1, 2]])
# Create matrix
matrix_b = np.array([[1, 3],
 [1, 2]])
# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [48]:
# Multiply two matrices
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [49]:
# Multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

In [50]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 4],
 [2, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [51]:
# Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])