In [2]:
print ("Hafezi")  #your name

Hafezi


1.1 Creating a Vector

In [3]:
# Load library
! pip install numpy
import numpy as np
# Create a vector as a row
vector_row = np.array([1, 2, 3])
# Create a vector as a column
vector_column = np.array([
    [1],
    [2],
    [3]])


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
vector_row

array([1, 2, 3])

In [6]:
vector_column

array([[1],
       [2],
       [3]])

In [7]:
vector_row.shape

(3,)

1.2 Creating a Matrix

In [8]:
# Load library
import numpy as np
# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [9]:
type(matrix) 

numpy.ndarray

In [10]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [12]:
matrix_object = np.asmatrix ([[1, 2],
                        [1, 2],
                        [1, 2]])

In [13]:
type (matrix_object)

numpy.matrix

In [14]:
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

1.3 Creating a Sparse Matrix

In [20]:
# Load libraries
import numpy as np
! pip install scipy
from scipy import sparse
# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [22]:
matrix_sparse

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>

In [23]:
print (matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [24]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [87]:
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

In [25]:
print(matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
