<a href="https://colab.research.google.com/github/hafezi1403/Hafezi/blob/main/Hafezi_1_30H_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
random_tensor = tf.random .uniform(
[5, ],
minval=0,
maxval=8,
dtype=tf.dtypes.float32,
seed=None,
name=None,
)
print(random_tensor)


tf.Tensor([1.4593601 7.0348263 7.335023  2.1823597 5.9457874], shape=(5,), dtype=float32)


In [3]:
tf.random.set_seed(5)
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [4]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print (tensor_indexed)
print (tensor_indexed[0:4])
print (tensor_indexed[3:-3])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)


In [5]:
tensor_two_d=tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
    ])
print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [6]:

tensor_three_d=tf.constant([
    [[2,20,3],
     [3,4,5]],
    [[4,78,6],
     [5,46,7]],
    [[6,103,8],
    [7,8,999]],
])
print(tensor_three_d[0,0,:])

tf.Tensor([ 2 20  3], shape=(3,), dtype=int32)


In [7]:
x_abs=tf.constant ([-2.25,3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [8]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.20000000298023224>

In [ ]:
x_abs_complex=tf.constant([-2.25+4.75j])
tf.abs(x_abs_complex)

In [9]:

tf.sqrt ((-2.25)**2+4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949020385742>

In [10]:
x_1 = tf.constant ([5,3,6,6,4,6],dtype=tf.int32)
x_2 = tf.constant ([7,6,2,6,7,11],dtype=tf.int32)
print (tf.divide (x_1 , x_2))


tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [11]:
x_1 = tf.constant ([[5,3,6,6,4,6],], dtype=tf.float32)
x_2 = tf.constant ([[7],[5],[3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1,x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [12]:
x_argmax=tf.constant([[2,20,30,3,6],
                      [3,11,16,1,8],
                      [14,45,23,5,27]])

print (x_argmax.shape)
print (tf.math.argmax(x_argmax,0))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)


In [13]:
x_argmax=tf.constant ([200,120,130,3,6])
print (tf.math.argmax(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [14]:
x_argmax=tf.constant([200,120,130,300,6])
print(tf.math.argmax(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)


In [15]:
x=tf.constant([[2,2],[3,3]])
y=tf.constant([[3,0],[1,4]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [16]:
tf.pow(tf.constant(2),tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [17]:

tensor_two_d=tf.constant([
    [1,-2,0],
    [3,5,100],
    [1,5,6],
    [2,3,8]
    ])
print(tensor_two_d.shape)
print(tf.math.reduce_sum(tensor_two_d,axis=0,keepdims=False,name=None))

(4, 3)
tf.Tensor([  7  11 114], shape=(3,), dtype=int32)


In [18]:
tf.math.top_k(tensor_two_d,k=1)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[  1],
       [100],
       [  6],
       [  8]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[0],
       [2],
       [2],
       [2]], dtype=int32)>)

In [19]:
x_1 = tf.constant ([[1,2,0],
                    [3,5,-1]])
x_2 = tf.constant ([[1,2,0,2],
                    [3,5,-1,2],
                    [4,5,6,0]])
print(x_1.shape,x_2.shape)
tf.linalg.matmul(
x_1,x_2,transpose_a=False,transpose_b=False, adjoint_a=False, adjoint_b=False,
a_is_sparse=False, b_is_sparse=False, output_type=None
)

(2, 3) (3, 4)


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[  7,  12,  -2,   6],
       [ 14,  26, -11,  16]], dtype=int32)>

In [20]:
print(x_1@x_2)

tf.Tensor(
[[  7  12  -2   6]
 [ 14  26 -11  16]], shape=(2, 4), dtype=int32)


In [21]:

x_1= tf.constant ([[1,2,0]])

x_2= tf.constant ([[1,2],
                  [3,5],
                  [4,5]])


In [22]:

tf.transpose (x_1)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [0]], dtype=int32)>

In [23]:

print(x_2)

tf.Tensor(
[[1 2]
 [3 5]
 [4 5]], shape=(3, 2), dtype=int32)


In [24]:
x_1= tf.constant ([[1,2,0]])

x_2= tf.constant ([[1,2],
                  [3,5],
                  [4,5]])

x_3=tf.constant ([[1,2,0,2],
                 [3,5,-1,2]])

print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)
#x_3.T=4.2
#x_2.T=3.2

(1, 3) (3, 2) (2, 4) (2, 3)


In [25]:
print(tf.transpose(x_3)@tf.transpose(x_2))


tf.Tensor(
[[ 7 18 19]
 [12 31 33]
 [-2 -5 -5]
 [ 6 16 18]], shape=(4, 3), dtype=int32)


In [26]:
tf.linalg.matmul(
x_3, x_2, transpose_a=True, transpose_b=True, adjoint_a=False, adjoint_b=False,
a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7, 18, 19],
       [12, 31, 33],
       [-2, -5, -5],
       [ 6, 16, 18]], dtype=int32)>

In [27]:
x_1 = tf.constant ([[1,2,0],
                    [3,5,-1]])


x_2 = tf.constant([[[5,1,4],
                    [34,15,1]],

                    [[1,2,2],
                     [5,3,2]],

                      [[2,2,3],
                       [1,1,1]]])

print(x_1)
print(x_2)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 5  1  4]
  [34 15  1]]

 [[ 1  2  2]
  [ 5  3  2]]

 [[ 2  2  3]
  [ 1  1  1]]], shape=(3, 2, 3), dtype=int32)


In [28]:

x_1 = tf.constant([[10,0],
                    [1,2]])


x_2 = tf.constant([[1,2,2],
                    [5,3,2]])

print(tf.linalg.matmul(x_1,x_2))

tf.Tensor(
[[10 20 20]
 [11  8  6]], shape=(2, 3), dtype=int32)


In [29]:
tensor_two_d=tf.constant([[1,-2,0],
                          [3,5,100],
                          [1,5,6],
                          [2,3,8]],dtype=tf.float16)

tensor_out_d=tf.constant([[1,0,0],
                          [0,5,0],
                          [0,0,6],
                          [0,0,0]],dtype=tf.float16)
###(m-n <= lower) and (n-m <= upper)
# m--rows , n---columns

tf.linalg.band_part(tensor_two_d,-1,0)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [3., 5., 0.],
       [1., 5., 6.],
       [2., 3., 8.]], dtype=float16)>

In [30]:

tensor_two_d_m_n=tf.constant([[1,-1,-2],
                              [1,0,-1],
                              [2,1,0],
                              [3,2,1]],dtype=tf.float16)



tensor_two_d_n_m=tf.constant([[0,1,2],
                              [-1,0,1],
                              [-2,-1,0],
                              [-3,-2,-1]],dtype=tf.float16)

In [31]:
tensor_two_d=tf.constant([[1,-2,0],
                          [3,5,100],
                          [1,5,6]],dtype=tf.float32)

tensor_two_d_inv=tf.linalg.inv(tensor_two_d)

In [32]:

tensor_two_d@tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  7.4505806e-09,  0.0000000e+00],
       [ 1.6391277e-07,  1.0000000e+00,  4.4703484e-08],
       [-5.2154064e-08,  7.4505806e-08,  1.0000000e+00]], dtype=float32)>