<a href="https://colab.research.google.com/github/hafezi1403/Hafezi/blob/main/Video_DL_1_30_Second.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:

tensor_two_d=tf.constant([[1,-2,0],
                          [3,5,100],
                          [1,5,6]],dtype=tf.float32)

s,u,v=tf.linalg.svd(tensor_two_d)
print(s)
print(u)
print(v)

tf.Tensor([100.3663      5.1059036   1.2371687], shape=(3,), dtype=float32)
tf.Tensor(
[[-7.4980810e-04 -3.7569830e-01  9.2674178e-01]
 [ 9.9803799e-01 -5.8300879e-02 -2.2827482e-02]
 [ 6.2606096e-02  9.2490643e-01  3.7500489e-01]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.03044816  0.07330841  0.99684453]
 [ 0.0528536   0.9957936  -0.07484547]
 [ 0.998138   -0.05496572 -0.02644547]], shape=(3, 3), dtype=float32)


In [3]:
A=np.array([[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]])

B=np.array([[2,9,0,3,0],
            [3,6,8,-2,2],
            [1,3,5,0,1],
            [3,0,2,0,5]])
print(A.shape)
print(B.shape)
print("Matmul c=: \n")
print(np.matmul(A,B), "\n")
print("Einsum c=:\n")
print(np.einsum("ij,jk -> ik",A,B))

(3, 4)
(4, 5)
Matmul c=: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]] 

Einsum c=:

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [4]:
A=np.array([[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]])


B=np.array([[2,9,0,3],
            [3,6,8,-2],
            [1,3,5,0]])

print(A.shape,B.shape)
print("Hardamond c=:\n")
print(A*B, "\n")

print("Einsum c=:\n")
print(np.einsum('ij,ij -> ij',A,B))

(3, 4) (3, 4)
Hardamond c=:

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]] 

Einsum c=:

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [5]:
A=np.array([[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]])

print("Transposed A=:\n")
print(A.T, "\n")

print("Einsum Transpose A=:\n")
print(np.einsum("ij -> ji",A))

Transposed A=:

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]] 

Einsum Transpose A=:

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


In [6]:
A=np.array([[[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]],

            [[1,3,1,22],
             [0,2,2,0],
             [1,5,4,1]]])

B=np.array([
            [[2,9,0,3,0],
            [3,6,8,-2,2],
            [1,3,5,0,1],
            [3,0,2,0,5]],

           [[1,0,0,3,0],
            [3,0,4,-2,2],
            [1,0,2,0,0],
            [3,0,1,1,0]]])
print(A.shape,B.shape)

print("Batch Muitiplication c=:\n")
print(np.matmul(A,B),"\n")

print("Einsum c=:\n")
print(np.einsum('bij,bjk -> bik', A,B))

(2, 3, 4) (2, 4, 5)
Batch Muitiplication c=:

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]] 

Einsum c=:

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [7]:
A=np.array([[[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]],

            [[1,3,1,22],
             [0,2,2,0],
             [1,5,4,1]]])
print("sum A=: \n")
print(np.sum(A), "\n")

print("Einsum A=:\n")
print(np.einsum('bij -> ' ,A))

sum A=: 

72 

Einsum A=:

72


In [8]:

A=np.array([[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]])
print("Axis 0 sum A=:\n")
print(np.sum(A,axis=0),"\n")

print("Einsum A=:\n")
print(np.einsum('ij -> j' ,A))
print("---------------------------")

print("Axis 1 sum A=:\n")
print(np.sum(A,axis=1), "\n")

print("Einsum A=:\n")
print(np.einsum('ij -> i' ,A))

Axis 0 sum A=:

[ 5  9 11  5] 

Einsum A=:

[ 5  9 11  5]
---------------------------
Axis 1 sum A=:

[15  5 10] 

Einsum A=:

[15  5 10]


In [9]:
A=np.random.randn(2,4,4,2) #bcij
B=np.random.randn(2,4,4,1) #bcik

In [10]:
np.einsum("bcik,bcij -> bckj", B,A).shape

(2, 4, 1, 2)

In [11]:
np.matmul(np.transpose(B,(0,1,3,2)),A).shape

(2, 4, 1, 2)

In [12]:
x_reshape = tf.constant([[3,5,6,6],
                         [4,6,-1,2]])

print(tf.reshape(x_reshape, [-1]))
print(tf.reshape(x_reshape, [8]))

tf.Tensor([ 3  5  6  6  4  6 -1  2], shape=(8,), dtype=int32)
tf.Tensor([ 3  5  6  6  4  6 -1  2], shape=(8,), dtype=int32)


In [13]:
tf.transpose(x_reshape)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 5,  6],
       [ 6, -1],
       [ 6,  2]], dtype=int32)>

In [14]:
t1= [[1,2,3],
     [4,5,6]]

t2= [[7,8,9],
     [10,11,12]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1, t2], axis = 0)

(2, 3)
(2, 3)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [15]:
tf.stack([t1,t2], axis = 0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [16]:
tf.concat([tf.expand_dims(t, axis = 0) for t in [t1,t2]], axis = 0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [17]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(params.shape)
params[1:3+1]

(6,)


<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [18]:
tf.gather(params, [0,5,3], axis = 0)

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [19]:
params = tf.constant([

                      [[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]]

                       ])
print(params.shape)
tf.gather(params, [2,0], axis = 1)

(1, 4, 3)


<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[20., 21., 22.],
        [ 0.,  1.,  2.]]], dtype=float32)>

In [20]:
indices = [[2]]

params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(1, 2), dtype=string, numpy=array([[b'e', b'f']], dtype=object)>

In [21]:
indices = [[0,1],
           [1,0]],


params = [[['a0', 'b0'],
           ['c0', 'd0']],

           [['a1', 'b1'],
            ['c1', 'd1']]]

In [22]:
tensor_two_d=tf.constant([[1,2,0],
                          [3,5,-1],
                          [1,5,6],
                          [2,3,8]])

print(tensor_two_d.shape)

(4, 3)


In [23]:
tensor_two_d = [[1,2,0],
                [3,],
                [1,5,6,5,6],
                [2,3]]

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [24]:

print(tf.RaggedTensor.from_row_lengths(
      values=[3,1,4,1,5,9,2,6],
      row_lengths=[4,0,3,1,0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [25]:
tf.gather_nd(params, indices, batch_dims = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']]], dtype=object)>

In [26]:
tensor_sparse = tf.SparseTensor(
    indices=[[1,1],[3,4]], values = [11,56], dense_shape = [5,6]
)

In [27]:
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [28]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [29]:
tensor_string = tf.constant(['hello', 'i am', 'a string'])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [30]:
tf.strings.join(tensor_string, separator ="")

<tf.Tensor: shape=(), dtype=string, numpy=b'helloi ama string'>

In [31]:

tf.strings.join(tensor_string, separator =' ')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello i am a string'>

In [32]:
tf.strings.join(tensor_string, separator ="**")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello**i am**a string'>

In [33]:
x = tf.constant([1,2])

In [34]:

x_var = tf.Variable(x)
print(x_var)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [36]:
x_var = tf.Variable(x, name = 'var1')
print(x_var)


<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [37]:
x_var.assign_sub([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [38]:
x_var.assign_add([5,8])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([3, 6], dtype=int32)>

In [39]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)

print(x_var)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.20000000298023224>


In [40]:
print(x_var.device)

/job:localhost/replica:0/task:0/device:CPU:0


In [41]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)

with tf.device('CPU:0'):
  x_tensor = tf.constant(0.2)

print(x_var.device)

print(x_tensor.device)


/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0


In [42]:

with tf.device('CPU:0'):
  x_1 = tf.constant([1,3,4])
  x_2 = tf.constant([1])

with tf.device('GPU:0'):
  x_3 = x_1 + x_2

print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 4 5], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
